tcp_routes_config:
  amqp_tcp_route_enabled: enabled_by_default
  amqp_tls_tcp_route_enabled: enabled_by_default
  cf_credentials:
    identity: solace_router
    password: '1234'
  mqtt_tcp_route_enabled: enabled_by_default
  mqtt_tls_tcp_route_enabled: enabled_by_default
  mqtt_ws_tcp_route_enabled: enabled_by_default
  mqtt_wss_tcp_route_enabled: enabled_by_default
  rest_tcp_route_enabled: enabled_by_default
  rest_tls_tcp_route_enabled: enabled_by_default
  smf_tcp_route_enabled: enabled_by_default
  smf_tls_tcp_route_enabled: enabled_by_default
  smf_zip_tcp_route_enabled: enabled_by_default
  web_messaging_tcp_route_enabled: enabled_by_default
  web_messaging_tls_tcp_route_enabled: enabled_by_default
